/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#2b5ab5",
        "primary-container": "#4874cf",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b0c6ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001945",
        "on-primary-fixed-variant": "#00429c",
        "on-primary-container": "#ffffff",
        secondary: "#005faf",
        "secondary-container": "#54a0fe",
        "secondary-fixed": "#d4e3ff",
        "secondary-fixed-dim": "#a5c8ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001c3a",
        "on-secondary-fixed-variant": "#004786",
        "on-secondary-container": "#003567",
        tertiary: "#006493",
        "tertiary-container": "#007eb8",
        "tertiary-fixed": "#cae6ff",
        "tertiary-fixed-dim": "#8dcdff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001e30",
        "on-tertiary-fixed-variant": "#004b70",
        "on-tertiary-container": "#00060d",
        surface: "#f3faff",
        "surface-bright": "#f3faff",
        "surface-dim": "#c7dde9",
        "surface-variant": "#cfe6f2",
        "surface-container": "#dbf1fe",
        "surface-container-low": "#e6f6ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#d5ecf8",
        "surface-container-highest": "#cfe6f2",
        "surface-tint": "#2b5bb5",
        "on-surface": "#071e27",
        "on-surface-variant": "#414754",
        "on-background": "#071e27",
        background: "#f3faff",
        outline: "#727785",
        "outline-variant": "#c1c6d6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#1e333c",
        "inverse-on-surface": "#dff4ff",
        "inverse-primary": "#b0c6ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
